# Generated by Django 2.2.4 on 2019-08-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourdata',
            name='number_of_district',
        ),
        migrations.RemoveField(
            model_name='ourdata',
            name='population',
        ),
    ]
