# Generated by Django 2.2.4 on 2019-09-15 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_auto_20190831_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=20)),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('date_of_contract', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_of_contract', models.DateTimeField(default=django.utils.timezone.now)),
                ('days_remained', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.AddField(
            model_name='ourdata',
            name='number_of_district',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ourdata',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ourdata',
            name='region',
            field=models.CharField(choices=[('', 'Select region'), ('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Njombe', 'Njombe'), ('Pemba North', 'Pemba North'), ('Pemba South', 'Pemba South'), ('Pwani', 'Pwani'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Simiyu', 'Simiyu'), ('Singida', 'Singida'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga'), ('Zanzibar North', 'Zanzibar North'), ('Zanzibar South', 'Zanzibar South'), ('Zanzibar Central', 'Zanzibar Central'), ('Zanzibar West', 'Zanzibar West')], max_length=50),
        ),
    ]
